version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: skogoreveduard/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    image: skogoreveduard/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: skogoreveduard/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media
    ports:
      - 9000:80